name: data1202sp25
channels:
  - conda-forge
dependencies:
  - jupyterhub-singleuser>=3.0,<4.0
  - python=3.10
  - nbgitpuller>=1.1.0
  - pip
  - nb_conda_kernels
  - jupyter
  - jupyterlab
  - ipykernel
  - ipython_genutils
  - jinja2=3.1.4
  - jupyter-resource-usage>=1.0
  - nbformat
  - ipywidgets
  - notebook
  - jupytext
  - anaconda::nbconvert
  - conda-forge::pandoc
  - nbclassic
  - pandas=2.2.3
  - numpy=2.1.1
  - matplotlib=3.9.2
  - scipy=1.14.1
  - seaborn=0.13.2
  - plotly
  - altair
  - scikit-learn=1.5.1
  - requests=2.32.3
  - beautifulsoup4=4.12.3
  - lxml=5.3.0
  - html5lib=1.1
  - imbalanced-learn=0.11.0
  - graphviz
  - datascience
  - pip:
      - dill==0.3.7
      - otter-grader==6.0.4
      - scikit-learn-extra
      - gspread
      - pypdf